services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - myNetwork
    tty: true
    container_name: nginx
    ports:
      - 8080:80
    depends_on:
      - node
      - mysql

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node
    volumes:
      - ./node:/usr/src/app/
    networks:
      - myNetwork
    tty: true
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 && mysql -u root -proot nodedb < backup.sql
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL-USER=root
    networks:
      - myNetwork

networks:
  myNetwork: